name: Style

on: [push, pull_request]

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure git credentials
        run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.3"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Style checking
        run: npm run lint:check
